In [69]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import CountVectorizer
import streamlit as st
from sklearn.naive_bayes import MultinomialNB , BernoulliNB

In [68]:
!pip install streamlit

Collecting streamlit
  Downloading streamlit-1.58.0-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.3-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.3.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.49.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.14.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.22.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.18)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.6.17)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2026.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.58.0-py3-none-any.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 50.1 MB/s eta 0:00:00
Downloading pydeck-0.9.3-py2.py3-none-any.whl (11.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 58.8 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.3 streamlit-1.58.0

In [3]:
from google.colab import files
uploaded = files.upload()

Saving spam.csv to spam.csv

In [48]:
df = pd.read_csv("spam.csv")

In [49]:
df.iloc[0]

Category                                                  ham
Message     Go until jurong point, crazy.. Available only ...
Name: 0, dtype: object

In [50]:
df.describe()

       Category                 Message
count      5572                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4825                      30

In [51]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [52]:
df.drop_duplicates()

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5157 rows x 2 columns]

In [53]:
df['Category'] = df['Category'].map({'ham': 'Not Spam', 'spam': 'Spam'})
df.head()

   Category                                            Message
0  Not Spam  Go until jurong point, crazy.. Available only ...
1  Not Spam                      Ok lar... Joking wif u oni...
2      Spam  Free entry in 2 a wkly comp to win FA Cup fina...
3  Not Spam  U dun say so early hor... U c already then say...
4  Not Spam  Nah I don't think he goes to usf, he lives aro...

In [54]:
x = df['Message']
y = df['Category']

In [55]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [56]:
cv = CountVectorizer(stop_words='english')
feature = cv.fit_transform(x_train)

In [57]:
model1 = MultinomialNB()
model1.fit(feature,y_train)

model2 = BernoulliNB()
model2.fit(feature,y_train)

BernoulliNB()

In [58]:
y_pred = model1.predict(cv.transform(x_test))
print(accuracy_score(y_test,y_pred))

y_pred2 = model2.predict(cv.transform(x_test))
print(accuracy_score(y_test,y_pred2))

0.9865470852017937
0.9757847533632287

In [61]:
message = cv.transform(["you won a lottery. Congrates"]).toarray()
result = model1.predict(message)
print(result)

message = cv.transform(["you won a lottery. Congrates"]).toarray()
result = model2.predict(message)
print(result)

['Spam']
['Not Spam']

In [65]:
message = cv.transform(["lets watch movie together"]).toarray()
result = model1.predict(message)
print(result)

message = cv.transform(["u won fifa ticket congrates , click here"]).toarray()
result = model1.predict(message)
print(result)

message = cv.transform(["hi , he texted me today"]).toarray()
result = model1.predict(message)
print(result)

['Not Spam']
['Spam']
['Not Spam']

In [70]:
def predict(messages):
  input_message = cv.transform([messages]).toarray()
  result = model1.predict(input_message)
  return result

st.header("SPAM DETECTION")

input_message = st.text_input("Enter your message")

if st.button('Predict'):
  result = predict(input_message)
  st.markdown(result)

2026-07-03 15:51:17.444 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-03 15:51:17.651
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py [ARGUMENTS]
2026-07-03 15:51:17.655 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-03 15:51:17.657 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-03 15:51:17.660 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-03 15:51:17.664 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-03 15:51:17.669 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-03 15:51:17.671 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-03 15:51:17.673 Session state does not function when running a script without `streamlit run`
2026-07-03 15:51:17.675 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-03 15:51:17.678 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-03 15:51:17.679 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-03 15:51:17.681 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-03 15:51:17.682 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-03 15:51:17.684 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-03 15:51:17.687 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-03 15:51:17.689 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-03 15:51:17.696 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.